### ISSUE TITLE
Final Project Submission

### ISSUE THREAD

**Issue by codelibra** [DS-GA3001-015/Final-Project-Airbnb#2]
Hello , 
Submitting the final project 68b0da2cbab1d17def4cb31ba942b1650493c44f

Project report: https://github.com/DS-GA3001-015/Final-Project-Airbnb/blob/master/presentation/DataViz_Presentation.Rmd
Slides: https://codelibra.github.io
Shiny app: https://itslimelight.shinyapps.io/impact--airbnb/

Please let us know in case any other information is required. @tbrambor @edufierro 

Thanks!

**Comment by tbrambor** [comment]
**Comments for the Group:**

The underlying idea of comparing private vs. commercial AirBnB rentals is well taken and followed through, and the resulting visualizations are well organized. Fundamentally, I would have preferred to organize the visuals on that comparison. As it stands, the user is often provided bar charts on each of the two types of AirBnB listings and is asked to compare across different charts. You could remove this addtl. mental step. Bar charts are the preferred methods of comparison and are no doubt useful. However, some other innovative ways to visualize the information (e.g. with informative scatter plots, heat maps etc.) would have shown a few more ways to map information to visuals.
The shiny map is well implemented but perhaps allows too many interactive choices. I found myself struggling going through the choices and Eduardo noted a similar assessment.

There was meant to be a single publicly accessible website component. As it stands, there is a GitHub document which restricts the use of static plots (though some may be interactive when hosted appropriately) and an accompanying shiny app. Ideally, these two components would be combined for a single public facing website presentation.

The code is well organized and and provides a good insight into the work you put into the project. A dedicated process book, however, seems to be missing. 

**Overall Grade: A-**
